mahmoud-birdsol/kjora

package.json, resources/js/Components/Avatar.vue, resources/js/Components/Chat/ConversationCard.vue, resources/js/Layouts/Partials/Navbar.vue, resources/js/app.js, yarn.lock
=> CU-8669nuxmk/As-a-user-I-want-to-view-the-player-photo-in-a-light-box-large-when-I-click-on-it

.gitignore, app/Contracts/GeolocatorInterface.php, app/DataTransferObjects/Geolocation.php, app/Http/Kernel.php, app/Http/Middleware/LocationDetector.php, app/Models/User.php, app/Nova/User.php, app/Services/Geolocator/ClientIpInfo.php, app/Services/Geolocator/GeoLocatorApiInterface.php, app/Services/Geolocator/GeolocatorApiAdapter.php, app/Services/Geolocator/IPGeolocationApi.php, app/Services/Geolocator/IpInfo.php, config/services.php, database/factories/UserFactory.php, database/migrations/2023_03_05_103507_add_last_geolocation_to_users_table.php, resources/js/Components/PlayerCards/MainPlayerCard.vue, resources/js/Layouts/Partials/Navbar.vue, routes/web.php
As-a-user-when-I-visit-the-system-it-should-automatically-detect-my-location
=> CU-8669nuweb/As-a-user-when-I-visit-the-system-it-should-automatically-detect-my-location

app/Http/Controllers/Auth/PasswordController.php, resources/js/Components/MoreBtn.vue, resources/js/Pages/Auth/UpdatePassword.vue, resources/js/Pages/More.vue, routes/web.php
CU-8669nvah4/As-a-user-I-want-to-update-my-password-in-the-settings-page
=> CU-8669nvah4/As-a-user-I-want-to-update-my-password-in-the-settings-page

app/Events/MessageReadEvent.php, app/Http/Controllers/Api/MarkMessageAsReadController.php, app/Http/Controllers/Api/NewMessagesController.php, app/Models/Message.php, resources/js/Components/Chat/ChatMessage.vue, resources/js/Components/Chat/ChatMessages.vue, resources/js/stores/chat.js, routes/api.php
CU-8669nx3n7/Update-the-chat-to-show-new-messages-highlighted
=> CU-8669nx3n7/Update-the-chat-to-show-new-messages-highlighted

resources/js/Components/Chat/UplaodChatFile.vue, resources/js/Components/UploadGalleryFile.vue
CU-8669nuyve/Fix-the-upload-popup-size-to-match-the-design
=> CU-8669nuyve/Fix-the-upload-popup-size-to-match-the-design

app/Http/Controllers/Auth/PasswordController.php, app/Http/Controllers/Auth/UserNameController.php, resources/js/Pages/Auth/UpdateUserName.vue, resources/js/Pages/More.vue, routes/web.php
CU-8669nvaja/As-a-user-I-want-to-update-my-username
=> CU-8669nvaja/As-a-user-I-want-to-update-my-username

app/Actions/Fortify/CreateNewUser.php
Phone numbers should be unique when registering
=> CU-8669nuymb/Phone-numbers-should-be-unique-when-registering-or-updating

app/Actions/Verification/CreateVerificationCode.php, app/Actions/Verification/DeleteExistingVerificationCodesForNumber.php, app/Actions/Verification/GenerateRandomCodeNumber.php, app/Actions/Verification/SendVerificationCodeSMSNotification.php, app/Actions/Verification/StoreVerificationCodeInDatabase.php, app/Http/Controllers/ResendVerificationCodeController.php, app/Http/Controllers/VerificationCodeController.php, app/Http/Kernel.php, app/Http/Requests/VerifyPhoneRequest.php, app/Http/Responses/RegisterSuccessfulResponse.php, app/Listeners/SendVerificationCodeNotification.php, app/Models/User.php, app/Notifications/VerificationCodeNotification.php, app/Providers/AppServiceProvider.php, app/Providers/EventServiceProvider.php, config/verification.php, database/migrations/2023_03_07_075416_create_verification_codes_table.php, resources/js/Pages/Auth/VerifyPhone.vue, resources/js/Pages/Verification/Create.vue, routes/web.php, yarn.lock
CU-8669nvagd/As-a-user-I-want-to-verify-my-phone-number-after-registration
=> CU-8669nvagd/As-a-user-I-want-to-verify-my-phone-number-after-registration

lang/ar.json, lang/en.json, resources/js/Components/RespondToInvitationModal.vue, resources/js/Pages/Invitation/Partials/InvitationCard.vue
CU-8669nwtnk/Update-the-invitation-accept-modal
=> CU-8669nwtnk/Update-the-invitation-accept-modal

lang/ar.json, lang/en.json, resources/js/Components/Comment.vue, resources/js/Pages/Gallery/Show.vue
CU-8669nwtpu/Update-the-gallery-page-translations
=> CU-8669nwtpu/Update-the-gallery-page-translations

lang/ar.json, lang/en.json, resources/js/Pages/Contact.vue
CU-8669nwtw6/Update-the-contact-page-translations
=> CU-8669nwtw6/Update-the-contact-page-translations

app/Http/Controllers/AdvertisementController.php, app/Http/Controllers/PlayerController.php, app/Jobs/CreateImpressionJob.php, app/Nova/Impression.php, resources/js/Pages/Home.vue, routes/web.php
CU-8669nuyaj/As-a-user-I-want-to-view-the-advertisements-on-the-home-page
=> CU-8669nuyaj/As-a-user-I-want-to-view-the-advertisements-on-the-home-page

app/Http/Controllers/Auth/UserEmailController.php, resources/js/Components/PlayerCards/MainPlayerCard.vue, resources/js/Components/ToolTip.vue, resources/js/Pages/Auth/UpdateEmail.vue, resources/js/Pages/Auth/UpdatePassword.vue, resources/js/Pages/Favorites/Index.vue, resources/js/Pages/Home.vue, resources/js/Pages/More.vue, routes/web.php
As a user I wan to update my-email address with verification cycle
=> CU-8669nuz4g/As-a-user-I-want-to-update-my-email-address-with-verification-cycle

resources/js/Components/Modal.vue, resources/js/Components/ProfileGallery.vue, resources/js/Pages/Gallery/Show.vue
CU-8669nuy36/As-a-user-I-want-to-delete-a-photo-or-video-from-the-details-page
=> CU-8669nuy36/As-a-user-I-want-to-delete-a-photo-or-video-from-the-details-page

package.json, resources/js/Components/PlayerCards/InvitationPlayerCard.vue, resources/js/Layouts/AppLayout.vue, resources/js/Pages/Hire/Index.vue, resources/js/Pages/Hire/Partials/HireCard.vue, resources/js/Pages/Invitation/Partials/InvitationCard.vue, yarn.lock
CU-8669nuz8r/Update-the-invitation-card-design
=> CU-8669nuz8r/Update-the-invitation-card-design

lang/ar.json, lang/en.json, resources/js/Pages/Auth/UpdatePassword.vue
CU-8669nwtx5/Update-the-update-password-page
=> CU-8669nwtx5/Update-the-update-password-page

lang/ar.json, lang/en.json, resources/js/Pages/Auth/UpdateEmail.vue, resources/js/Pages/More.vue
CU-8669nwtwq/Update-the-update-email-page
=> CU-8669nwtwq/Update-the-update-email-page

lang/ar.json, lang/en.json, resources/js/Pages/Auth/UpdateUserName.vue, resources/js/Pages/More.vue
CU-8669nwtxk/Update-the-update-username-page
=> CU-8669nwtxk/Update-the-update-username-page

lang/ar.json, lang/en.json, resources/js/Pages/Auth/UpdatePhone.vue, resources/js/Pages/More.vue
CU-8669nwtwx/Update-the-update-phone-number-page
=> CU-8669nwtwx/Update-the-update-phone-number-page

lang/ar.json, lang/en.json, resources/js/Pages/Upgrade.vue
CU-8669nwtxr/Update-the-upgrade-account-page
=> CU-8669nwtxr/Update-the-upgrade-account-page

lang/ar.json, lang/en.json, resources/js/Pages/Auth/Forms/VerifyEmailForm.vue, resources/js/Pages/Auth/VerifyEmail.vue
CU-8669nwtwf/Update-the-verify-email-page-translations
=> CU-8669nwtwf/Update-the-verify-email-page-translations

lang/ar.json, lang/en.json, resources/js/Pages/Auth/VerifyPhone.vue
CU-8669nwtwk/Update-the-verify-phone-number-page-translations
=> CU-8669nwtwk/Update-the-verify-phone-number-page-translations

lang/ar.json, lang/en.json, resources/js/Pages/Reviews/Show.vue
CU-8669nwtm3/Update-review-page-translations
=> CU-8669nwtm3/Update-review-page-translations

app/Http/Controllers/Api/NewMessagesController.php, app/Models/Message.php, resources/js/Components/Chat/ChatMessages.vue, resources/js/stores/chat.js, routes/api.php
CU-8669p0dd7/Hack-the-pusher-failing-to-send-messages-issue
=> CU-8669p0dd7/Hack-the-pusher-failing-to-send-messages-issue

lang/ar.json, lang/en.json, resources/js/Pages/TermsOfService.vue
CU-8669nwtqf/Update-the-terms-and-conditions-page-translations
=> CU-8669nwtqf/Update-the-terms-and-conditions-page-translations

lang/ar.json, lang/en.json, resources/js/Pages/PrivacyPolicy.vue, resources/js/Pages/TermsOfService.vue
CU-8669nwtq6/Update-the-privacy-policy-page-translations
=> CU-8669nwtq6/Update-the-privacy-policy-page-translations

resources/js/Pages/CookiesPolicy.vue
CU-8669nwtqq/Update-the-cookie-policy-page-translations
=> CU-8669nwtqq/Update-the-cookie-policy-page-translations

app/Models/ReportOption.php, app/Nova/ReportOption.php, app/Providers/AppServiceProvider.php, composer.json, composer.lock, database/migrations/2023_02_23_084228_create_report_options_table.php
CU-8669nwtv7/Update-the-report-options-to-be-translatable
=> CU-8669nwtv7/Update-the-report-options-to-be-translatable

app/Http/Controllers/Auth/UserEmailController.php, app/Http/Controllers/VerificationCodeController.php
CU-8669qmxqk/flash-msg-for-Email-update-confirmation-doesnt-close-nor-has-a-close--X-button
=> CU-8669qmxqk/flash-msg-for-Email-update-confirmation-doesnt-close-nor-has-a-close--X-button

resources/js/Layouts/AppLayout.vue, resources/js/Pages/Home.vue, resources/views/app.blade.php, tailwind.config.js
CU-8669qxcnr/In-almost-all-Buttons-in-Arabic-letters-are-seperated
=> CU-8669qxcnr/In-almost-all-Buttons-in-Arabic-letters-are-seperated

lang/ar.json, lang/en.json, resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
CU-8669qx59d/QA-translations-Fixes
=> CU-8669qx59d/QA-translations-Fixes

resources/js/Pages/Home.vue
CU-8669qmyvz/Filter-Range-in-home-is-displayed-with-blue-color-needs-to-change-primary-color
=> CU-8669qmyvz/Filter-Range-in-home-is-displayed-with-blue-color-needs-to-change-primary-color

resources/js/Pages/Home.vue
CU-860q90r0p/Grid-map-toggle-should-be-a-button-group-without-space-between
=> CU-860q90r0p/Grid-map-toggle-should-be-a-button-group-without-space-between

resources/js/Components/UploadSelfieModal.vue, resources/js/Pages/Auth/VerifyIdentity.vue
CU-8669t3xdy/Verify-identity-camera-not-working-on-mobile
=> CU-8669t3xdy/Verify-identity-camera-not-working-on-mobile

resources/js/Components/Chat/ChatForm.vue, resources/js/Layouts/ChatLayout.vue
CU-8669tra9t/Update-the-conversation-list-in-the-chat-show-page
=> CU-8669tra9t/Update-the-conversation-list-in-the-chat-show-page

resources/js/Components/Chat/ChatForm.vue
CU-860q90qz0/Hide-emoji-field-for-mobile-UI
=> CU-860q90qz0/Hide-emoji-field-for-mobile-UI

resources/js/Components/Avatar.vue, resources/js/Components/Chat/ChatForm.vue, resources/js/Components/Chat/ChatGallery.vue, resources/js/Components/Chat/ChatMessage.vue, resources/js/Components/Chat/ConversationCard.vue, resources/js/Components/Comment.vue, resources/js/Components/Maps/PlayersMap.vue, resources/js/Components/PlayerCards/InvitationPlayerCard.vue, resources/js/Components/PlayerCards/MainPlayerCard.vue, resources/js/Layouts/Partials/Navbar.vue, resources/js/Pages/Gallery/Show.vue, resources/js/Pages/Reviews/Show.vue
CU-8669t41hw/In-the-invitation-user-card-when-I-click-on-the-user-image-name-or-username-they-should-redirect-me-to-their-profile
=> CU-8669t41hw/In-the-invitation-user-card-when-I-click-on-the-user-image-name-or-username-they-should-redirect-me-to-their-profile

resources/js/Components/Chat/ChatForm.vue
CU-860q90qte/Chat-message-placeholder-text-needs-to-be-smaller-for-mobile-UI
=> CU-860q90qte/Chat-message-placeholder-text-needs-to-be-smaller-for-mobile-UI

resources/js/Components/UploadGalleryFile.vue
CU-8669t3kef/Video-cover-photo-in-gallery-not-showing
=> CU-8669t3kef/Video-cover-photo-in-gallery-not-showing

resources/js/Pages/Auth/VerifyPhone.vue
CU-860qp5azj/Remove-phone-verification-placeholder
=> CU-860qp5azj/Remove-phone-verification-placeholder

resources/js/Components/Chat/UplaodChatFile.vue, resources/js/Components/Crop.vue, resources/js/Components/FadeInTransition.vue, resources/js/Components/SlideDownTransition.vue, resources/js/Components/UploadGalleryFile.vue, resources/js/Components/UploadImageField.vue
CU-860qp5baw/Move-the-crop-functionality-to-the-same-upload-image-pop-with-a-toggle-view-not-another-overlay-popup
=> CU-860qp5baw/Move-the-crop-functionality-to-the-same-upload-image-pop-with-a-toggle-view-not-another-overlay-popup

resources/js/Components/Crop.vue, resources/js/Components/UploadImageField.vue
CU-860qqbq2y/Make-the-profile-picture-crop-to-be-circle-instead-of-square
=> CU-860qqbq2y/Make-the-profile-picture-crop-to-be-circle-instead-of-square
